spring.application.name=biblioteca
# Configuração do Servidor
server.port=8080
server.servlet.context-path=/

# Nome da Aplicação
spring.application.name=Sistema de Gestão de Livros

# Logging
logging.level.root=WARN
logging.level.br.com.christianamsberg.biblioteca=INFO
